### ISSUE TITLE
Restart tool bugs

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#191]
A few bugs identified when restarting a course:
- Player Effects aren't cleared
- Inventories aren't refreshed (i.e. consumables aren't refilled)

**Comment by steve4744** [comment]
Just to add to this, when the restart tool is used, the live timer starts at 1 instead of zero. Sounds an easy fix, but I've tried a few different tests and have been unable to get it to work satisfactorily - either the player gains an advantage by being able to move before the timer starts, or the finish time ends up out of sync by up to a second with the displayed time.

Maybe the reset should create a new session, and/or have a small (3-2-1) countdown?

**Comment by A5H73Y** [comment]
Hmmm, I think you're right with a delay... perhaps to avoid any bugs it should go through the full leave / join cycle but only teleport them right at the end. 
Needs some investigation into what that would look like

**Comment by A5H73Y** [comment]
Fixed in latest commit. 
Was as simple as silently leaving and rejoining the course, seems to work as expected.
