### ISSUE TITLE
Using blocks as ParkourTool places blocks for a very short time before removing them

### ISSUE THREAD

**Issue by URoulon** [A5H73Y/Parkour#300]
We're running 6.7.1 and tried to use the Barrier block as an exit tool.

Even with both AnybodyPlaceBreakBlocks and AdminPlaceBreakBlocks set to false, the block still gets placed
for a very short time allowing you to access blocked areas or to make some jumps easier.

**Comment by A5H73Y** [comment]
After doing some research and trying a few things I have established that it isn't entirely possibly due to the nature of client / server interaction: https://www.spigotmc.org/threads/remove-delay-on-cancel-place-event.369965/

I have set the priority of the event to cancel it sooner however the exploit is stil possible, there are a few work arounds:

- Use Adventure GameMode, this will prevent the client breaking / placing materials
- Use WorldGuard or similar, I assume this has a far more sophisticated way of working
- Design Courses in a way they can't be exploited, or change your ParkourTools to those that can't be placed.
