### ISSUE TITLE
When I install the plugin and it works. but when I restart the plugin is gone..

### ISSUE THREAD

**Issue by bitzbyhomekz** [A5H73Y/Parkour#48]
Just like in the title when I restart my server the plugin will be gone and the file and the jar is still in the plugins folder idk how or why did it happen. im only a beginner plss help me Dev. I really like your Plugin

**Comment by A5H73Y** [comment]
Going to need a lot more information than what you've provided to identify the problem. 
If you want to add me on Skype we can discuss is easier: iA5H73Y
Otherwise, please link your console.log so I can analyze the problem.

**Comment by bitzbyhomekz** [comment]
no errors in the console,,,, ill explain.. So first I drop the Parkour plugin in the plugins folder and then restart! after that it worked fine, and When I restart again, The Parkour plugin is gone but still the Parkour.Jar and the Parkour Folder is still in the Plugins Folder.

**Comment by A5H73Y** [comment]
This would be because the plugin failed to load successfully on start up, there must be an error message in the logs at start up, unless it's silently dying. 
I understand the stages, but I need technical information to investigate why it's not working now; the entire console.log will hopefully provide everything I need to know. If you want to keep it private, you can private message me it.

**Comment by bitzbyhomekz** [comment]
Good Day A5H73Y

          Well I certainley download a new one and it worked perfectly now,
Thank you and I appreciate your help, even I didnt buy your plugin you
still want to help :) btw ill send you the errors that ive found later. See
ya :)

2017-04-22 1:25 GMT-07:00 A5H73Y <notifications@github.com>:

**Comment by A5H73Y** [comment]
Thanks for the feedback :)
