### ISSUE TITLE
Unable to create databases on install?

### ISSUE THREAD

**Issue by GRRRillaNinja** [A5H73Y/Parkour#80]
I get this error many times. Checkpoints.yml, courses, players, etc all are created with no issues. Running 4.1 version of your plugin with Spigot 1.12
24.09 01:17:29 [Server] INFO Unable to create database! 
24.09 01:17:29 [Server] WARN [SQL] Defaulting to SQLite... 
24.09 01:17:29 [Server] ERROR ! [SQL] Connection problem: path to 'sqlite-db/plugins/Parkour': '/sqlite-db/plugins' does not exist

**Comment by A5H73Y** [comment]
Hey @GRRRillaNinja 
This is a recurring problem ever since Parkour uses SQLite, there is no known solution yet, other than another plugin using SQLite at the same time.
If you would like to add me on Skype or Discord (both are found on the spigot page), then I can attempt to finally find the solution.
Thanks
